title = "Koko"

[postgres]
host = "127.0.0.1"
port = 1234
user = "postgres"
password = "postgres"
dbname = "acdc_test"

[root]
username = "root"
password = "114514"

[jwt]
title = "JWT Middleware"
key = "excited"

[hotel]
max_room = 114514

[ticket]
page_size = 20