basePath: /api/v1
definitions:
  model.User:
    properties:
      phone:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  schema.AuthLoginRequestSchema:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  schema.AuthLoginResponseSchema:
    properties:
      code:
        type: integer
      expire:
        type: string
      token:
        type: string
    type: object
  schema.CommonFailureSchema:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
        - application/json
      parameters:
        - description: User request
          in: body
          name: userRequest
          required: true
          schema:
            $ref: '#/definitions/schema.AuthLoginRequestSchema'
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.AuthLoginResponseSchema'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schema.CommonFailureSchema'
      summary: Perform login.
  /user/all:
    get:
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      security:
        - ApiKeyAuth: []
      summary: List all users.
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
